<template>
  <div class="material-upload-container">
    <div class="upload-card">
      <h2 class="upload-title">{{ isEdit ? '编辑资料' : '上传资料' }}</h2>

      <a-form
        :model="formData"
        :rules="rules"
        ref="formRef"
        layout="vertical"
      >
        <a-form-item label="资料标题" name="title">
          <a-input
            v-model:value="formData.title"
            placeholder="请输入资料标题"
            size="large"
          />
        </a-form-item>

        <a-form-item label="资料分类" name="categoryId">
          <a-select
            v-model:value="formData.categoryId"
            placeholder="请选择分类"
            size="large"
          >
            <a-select-option
              v-for="cat in categories"
              :key="cat.id"
              :value="cat.id"
            >
              {{ cat.name }}
            </a-select-option>
          </a-select>
        </a-form-item>

        <a-form-item label="资料简介" name="description">
          <a-textarea
            v-model:value="formData.description"
            placeholder="请输入资料简介"
            :rows="4"
          />
        </a-form-item>

        <a-form-item label="资料正文（可选，不上传文件时可直接作为资料内容）" name="contentText">
          <a-textarea
            v-model:value="formData.contentText"
            placeholder="请输入较完整的资料内容。若未上传文件，系统会自动将此内容生成TXT资料。"
            :rows="10"
          />
        </a-form-item>

        <a-form-item label="封面图片" name="coverUrl">
          <a-upload
            list-type="picture-card"
            :file-list="coverFileList"
            :before-upload="beforeCoverUpload"
            @remove="handleCoverRemove"
            :max-count="1"
          >
            <div v-if="coverFileList.length < 1">
              <i class="fa fa-plus"></i>
              <div style="margin-top: 8px">上传封面</div>
            </div>
          </a-upload>
        </a-form-item>

        <a-form-item label="资料文件" name="fileUrl">
          <a-upload
            :file-list="fileList"
            :before-upload="beforeFileUpload"
            @remove="handleFileRemove"
            :max-count="1"
          >
            <a-button>
              <i class="fa fa-upload"></i>
              选择文件
            </a-button>
          </a-upload>
          <div class="upload-tip">
            支持格式：PDF、Word、Excel、PPT、Markdown、TXT
          </div>
        </a-form-item>

        <a-form-item label="文件类型" name="fileType" v-if="formData.fileUrl && !isAutoGeneratedFile">
          <a-select
            v-model:value="formData.fileType"
            placeholder="请选择文件类型"
            size="large"
          >
            <a-select-option value="PDF">PDF</a-select-option>
            <a-select-option value="WORD">Word</a-select-option>
            <a-select-option value="EXCEL">Excel</a-select-option>
            <a-select-option value="PPT">PPT</a-select-option>
            <a-select-option value="MARKDOWN">Markdown</a-select-option>
            <a-select-option value="TXT">TXT</a-select-option>
          </a-select>
        </a-form-item>

        <a-form-item label="价格（积分）" name="price">
          <a-input-number
            v-model:value="formData.price"
            :min="0"
            :max="100000"
            placeholder="请输入价格"
            size="large"
            style="width: 100%"
          />
        </a-form-item>

        <a-form-item label="标签" name="tags">
          <a-select
            v-model:value="formData.tags"
            mode="tags"
            placeholder="请输入标签，按回车添加"
            size="large"
          />
        </a-form-item>

        <a-form-item>
          <a-space>
            <a-button
              type="primary"
              size="large"
              @click="handleSubmit"
              :loading="uploading"
            >
              {{ isEdit ? '保存修改' : '立即上传' }}
            </a-button>
            <a-button size="large" @click="handleCancel">
              取消
            </a-button>
          </a-space>
        </a-form-item>
      </a-form>
    </div>
  </div>
</template>

<script>
import { ref, reactive, onMounted, computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { message } from 'ant-design-vue'
import materialService from '@/service/materialService'
import fileService from '@/service/fileService'
import ragService from '@/service/ragService'

export default {
  name: 'MaterialUpload',
  setup() {
    const route = useRoute()
    const router = useRouter()
    const formRef = ref()
    const uploading = ref(false)
    const categories = ref([])
    const coverFileList = ref([])
    const fileList = ref([])
    const isAutoGeneratedFile = ref(false)

    const isEdit = computed(() => !!route.params.id)

    const formData = reactive({
      title: '',
      categoryId: null,
      description: '',
      contentText: '',
      coverUrl: '',
      fileUrl: '',
      fileType: 'PDF',
      fileSize: 0,
      price: 0,
      tags: []
    })

    const rules = {
      title: [{ required: true, message: '请输入资料标题', trigger: 'blur' }],
      categoryId: [{ required: true, type: 'number', message: '请选择分类', trigger: 'change' }],
      description: [{ required: true, message: '请输入资料简介', trigger: 'blur' }],
      price: [{
        required: true,
        type: 'number',
        validator: (_rule, value) => {
          if (value === null || value === undefined || value === '') {
            return Promise.reject('请输入价格')
          }
          if (typeof value !== 'number') {
            return Promise.reject('价格必须为数字')
          }
          return Promise.resolve()
        },
        trigger: 'blur'
      }]
    }

    // 加载分类
    const loadCategories = async () => {
      try {
        const res = await materialService.getCategories()
        if (res.code === 0) {
          categories.value = res.data || []
        }
      } catch (error) {
        console.error('加载分类失败', error)
      }
    }

    // 加载资料详情（编辑模式）
    const loadMaterialDetail = async () => {
      if (!isEdit.value) return

      try {
        const res = await materialService.getMaterialDetail(route.params.id)
        if (res.code === 0) {
          const data = res.data
          Object.assign(formData, {
            title: data.title,
            categoryId: data.categoryId,
            description: data.description,
            contentText: data.contentText || '',
            coverUrl: data.coverUrl,
            fileUrl: data.fileUrl,
            fileType: data.fileType,
            fileSize: data.fileSize,
            price: data.price,
            tags: data.tags ? (typeof data.tags === 'string' ? data.tags.split(',').filter(t => t.trim()) : data.tags) : []
          })

          if (data.coverUrl) {
            coverFileList.value = [{
              uid: '-1',
              name: 'cover.jpg',
              status: 'done',
              url: data.coverUrl
            }]
          }

          if (data.fileUrl) {
            fileList.value = [{
              uid: '-1',
              name: data.fileName || 'file',
              status: 'done',
              url: data.fileUrl
            }]
          }
        }
      } catch (error) {
        message.error('加载资料详情失败')
        console.error(error)
      }
    }

    // 上传封面前
    const beforeCoverUpload = async (file) => {
      const isImage = file.type.startsWith('image/')
      if (!isImage) {
        message.error('只能上传图片文件')
        return false
      }

      const isLt2M = file.size / 1024 / 1024 < 2
      if (!isLt2M) {
        message.error('图片大小不能超过 2MB')
        return false
      }

      try {
        const res = await fileService.upload(file)
        if (res.code === 0 && res.data?.url) {
          formData.coverUrl = res.data.url
          coverFileList.value = [{
            uid: file.uid,
            name: file.name,
            status: 'done',
            url: res.data.url
          }]
          message.success('封面上传成功')
        }
      } catch (error) {
        message.error('封面上传失败')
        console.error(error)
      }

      return false
    }

    // 移除封面
    const handleCoverRemove = () => {
      formData.coverUrl = ''
      coverFileList.value = []
    }

    // 上传文件前
    const beforeFileUpload = async (file) => {
      const isLt50M = file.size / 1024 / 1024 < 50
      if (!isLt50M) {
        message.error('文件大小不能超过 50MB')
        return false
      }

      uploading.value = true
      try {
        const res = await fileService.upload(file)
        if (res.code === 0 && res.data?.url) {
          formData.fileUrl = res.data.url
          formData.fileSize = file.size
          fileList.value = [{
            uid: file.uid,
            name: file.name,
            status: 'done',
            url: res.data.url
          }]
          message.success('文件上传成功')
        }
      } catch (error) {
        message.error('文件上传失败')
        console.error(error)
      } finally {
        uploading.value = false
      }

      return false
    }

    // 移除文件
    const handleFileRemove = () => {
      formData.fileUrl = ''
      formData.fileSize = 0
      fileList.value = []
    }

    const ensureMaterialFile = async () => {
      if (formData.fileUrl) {
        return
      }

      const content = (formData.contentText || '').trim()
      if (!content) {
        throw new Error('请上传资料文件，或填写资料正文')
      }

      const autoFileName = `${formData.title || 'material'}-${Date.now()}.txt`
      const fileUrl = await fileService.uploadTextFile(autoFileName, content)
      formData.fileUrl = fileUrl
      formData.fileType = 'TXT'
      formData.fileSize = new TextEncoder().encode(content).length
      isAutoGeneratedFile.value = true

      fileList.value = [{
        uid: `auto-${Date.now()}`,
        name: autoFileName,
        status: 'done',
        url: fileUrl
      }]
    }

    const triggerVectorize = async (materialId) => {
      if (!materialId || !formData.fileUrl) {
        return
      }

      const vectorRes = await ragService.vectorizeMaterial(
        materialId,
        formData.fileUrl,
        formData.fileType
      )

      if (vectorRes.code !== 0) {
        throw new Error('向量化请求失败')
      }

      if (vectorRes.data && vectorRes.data.success === false) {
        throw new Error(vectorRes.data.error || '向量化失败')
      }
    }

    // 提交
    const handleSubmit = async () => {
      try {
        await ensureMaterialFile()
        await formRef.value.validate()

        uploading.value = true

        // 转换tags数组为逗号分隔的字符串
        const submitData = {
          ...formData,
          tags: Array.isArray(formData.tags) ? formData.tags.join(',') : formData.tags
        }

        if (isEdit.value) {
          // 更新
          const res = await materialService.updateMaterial(route.params.id, submitData)
          if (res.code === 0) {
            try {
              await triggerVectorize(route.params.id)
              message.success('更新成功，向量索引已刷新')
            } catch (vectorError) {
              message.warning(`资料已更新，但向量化失败：${vectorError.message || '未知错误'}`)
            }
            router.push(`/material/${route.params.id}`)
          }
        } else {
          // 上传
          const res = await materialService.uploadMaterial(submitData)
          if (res.code === 0) {
            try {
              await triggerVectorize(res.data.id)
              message.success('上传成功，资料已可用于RAG检索')
            } catch (vectorError) {
              message.warning(`资料已上传，但向量化失败：${vectorError.message || '未知错误'}`)
            }
            router.push(`/material/${res.data.id}`)
          }
        }
      } catch (error) {
        if (error.errorFields) {
          message.error('请完善表单信息')
        } else {
          message.error('操作失败：' + (error.message || '未知错误'))
        }
        console.error(error)
      } finally {
        uploading.value = false
      }
    }

    // 取消
    const handleCancel = () => {
      router.back()
    }

    onMounted(() => {
      loadCategories()
      loadMaterialDetail()
    })

    return {
      formRef,
      formData,
      rules,
      uploading,
      categories,
      coverFileList,
      fileList,
      isEdit,
      isAutoGeneratedFile,
      beforeCoverUpload,
      handleCoverRemove,
      beforeFileUpload,
      handleFileRemove,
      handleSubmit,
      handleCancel
    }
  }
}
</script>

<style scoped>
.material-upload-container {
  padding: 20px;
  max-width: 900px;
  margin: 0 auto;
}

.upload-card {
  background: #fff;
  padding: 40px;
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0,0,0,0.05);
}

.upload-title {
  font-size: 24px;
  font-weight: 600;
  margin-bottom: 30px;
  text-align: center;
}

.upload-tip {
  margin-top: 8px;
  font-size: 12px;
  color: #999;
}
</style>
